In [2]:
%matplotlib widget
from utils import *
from DataReader import DataReader
np.set_printoptions(precision=2, suppress=True)
np.random.seed(123)

<font color='#99ff99'>
<Center><H1>Chapter2 Python Review</h1></center>
</font>

<font color='#99ff99'>
<H2>2.1 Python Basics </h2>
<H4> - 2D Data Index
</font>

In [3]:
# 2D matrix N x 3
N = 10
table = np.random.rand(N,3)*100
print(table)

[[69.65 28.61 22.69]
 [55.13 71.95 42.31]
 [98.08 68.48 48.09]
 [39.21 34.32 72.9 ]
 [43.86  5.97 39.8 ]
 [73.8  18.25 17.55]
 [53.16 53.18 63.44]
 [84.94 72.45 61.1 ]
 [72.24 32.3  36.18]
 [22.83 29.37 63.1 ]]


In [4]:
# indexing
student0_calculus = table[0, 0]
print(student0_calculus)
student0_physics = table[0, 1]
print(student0_physics) 
student0_all = table[0, :]
print(student0_all)

69.64691855978616
28.613933495037948
[69.65 28.61 22.69]


<font color='#99ff99'>
<H4> - 2D Data Index: from - to
</font>

In [5]:
# indexing from to
student_0to3 = table[0:4,:]
print(student_0to3)
student_0to3 = table[:4,:]
print(student_0to3)

[[69.65 28.61 22.69]
 [55.13 71.95 42.31]
 [98.08 68.48 48.09]
 [39.21 34.32 72.9 ]]
[[69.65 28.61 22.69]
 [55.13 71.95 42.31]
 [98.08 68.48 48.09]
 [39.21 34.32 72.9 ]]


In [5]:
# indexing from to
student_7to9 = table[7:10,:]
print(student_7to9)
student_7to9 = table[7:,:]
print(student_7to9)

[[84.94 72.45 61.1 ]
 [72.24 32.3  36.18]
 [22.83 29.37 63.1 ]]
[[84.94 72.45 61.1 ]
 [72.24 32.3  36.18]
 [22.83 29.37 63.1 ]]


<font color='#99ff99'>
<H4> - 2D Data Index: negative index
</font>

In [6]:
# negative index
lastIndex, _ = table.shape
student_last = table[lastIndex-1]
print(student_last)

student_last = table[-1,:]
print(student_last)

[22.83 29.37 63.1 ]
[22.83 29.37 63.1 ]


<font color='#99ff99'>
<H4> - If else </h4>
</font>

In [7]:
# if, else, elif
average = np.mean(student_last)
print(average)
if (average >= 90):
    print('Grade: A')
elif (average >= 80):
    print('Grade: B')
elif (average >= 70):
    print('Grade: C')
else:
    print('Grade: D')

38.43178003740909
Grade: D


<font color='#99ff99'>
<H4>- Function </h4>
</font>

In [8]:
# function
def printGrade(average):
    if (average >= 80):
        print('Grade: A')
    elif (average >= 60):
        print('Grade: B')
    elif (average >= 40):
        print('Grade: C')
    else:
        print('Grade: D')

<font color='#99ff99'>
<H4>- Loops </h4>
</font>

In [9]:
# print Nx3 matrix line by line with for loop
for i in range(0, 10):
    average = np.mean(table[i, :])
    printGrade(average)

Grade: C
Grade: C
Grade: B
Grade: C
Grade: D
Grade: D
Grade: C
Grade: B
Grade: C
Grade: D


In [10]:
# print Nx3 matrix line by line with for while
index = 0
while index < 10:
    average = np.mean(table[index, :])
    printGrade(average)
    index += 1

Grade: C
Grade: C
Grade: B
Grade: C
Grade: D
Grade: D
Grade: C
Grade: B
Grade: C
Grade: D


<font color='#99ff99'>
<H4>- Class </h4>
</font>

In [11]:
# class
class Scores():
    def __init__(self, data):
        self.calculus = table[:, 0:1]
        self.physics = table[:, 1:2]
        self.chemistry = table[:, 2:3]
s = Scores(table)
print(table)
print(s.calculus)
print(s.physics)
print(s.chemistry)


[[69.65 28.61 22.69]
 [55.13 71.95 42.31]
 [98.08 68.48 48.09]
 [39.21 34.32 72.9 ]
 [43.86  5.97 39.8 ]
 [73.8  18.25 17.55]
 [53.16 53.18 63.44]
 [84.94 72.45 61.1 ]
 [72.24 32.3  36.18]
 [22.83 29.37 63.1 ]]
[[69.65]
 [55.13]
 [98.08]
 [39.21]
 [43.86]
 [73.8 ]
 [53.16]
 [84.94]
 [72.24]
 [22.83]]
[[28.61]
 [71.95]
 [68.48]
 [34.32]
 [ 5.97]
 [18.25]
 [53.18]
 [72.45]
 [32.3 ]
 [29.37]]
[[22.69]
 [42.31]
 [48.09]
 [72.9 ]
 [39.8 ]
 [17.55]
 [63.44]
 [61.1 ]
 [36.18]
 [63.1 ]]
